[pytest]
testpaths = tests

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

addopts = --alluredir=allure-results

markers =
    wp: tests for word press api
    ya_disk: tests for yandex disk api
    ya_disk_files: tests for yandex disk api working with files